name: Publish Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  publish_package:
    permissions: 
      contents: write
      packages: write 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0 || echo '0.0.0')"

      - name: Calculate next version
        id: next_version
        run: echo "::set-output name=next_version::$(echo "${{ steps.latest_tag.outputs.latest_tag }}" | awk -F. '{$NF = $NF + 1;} 1' OFS=. || echo '1.0.0')"

      - name: Generate and apply version tag
        id: version_tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "${{ steps.next_version.outputs.next_version }}"
          echo "::set-output name=new_tag::${{ steps.next_version.outputs.next_version }}"

      - name: Push new tag
        if: steps.version_tag.outputs.new_tag != ''
        run: git push origin "${{ steps.version_tag.outputs.new_tag }}" || echo "Tag already exists, skipping push"

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
