name: Build and Publish Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: front-end-framework
          path: target/front-end-framework.jar

      - name: Generate and apply version tag
        id: version_tag
        run: |
          LAST_TAG=$(git describe --abbrev=0 --tags)
          IFS='.' read -ra VER <<< "$LAST_TAG"
          MAJOR="${VER[0]}"
          MINOR="${VER[1]}"
          PATCH="${VER[2]}"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          git tag "$NEW_VERSION"
          echo "::set-output name=new_tag::$NEW_VERSION"

      - name: Push new tag
        if: steps.version_tag.outputs.new_tag != ''
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git push origin ${{ steps.version_tag.outputs.new_tag }}
