name: Build and Publish Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: front-end-framework
          path: target/front-end-framework.jar

      - name: Generate and apply version tag
        id: version_tag
        run: |
          VERSION=$(git tag --sort=-version:refname | head -n 1)
          if [[ -z "$VERSION" ]]; then
            NEW_VERSION="1.0.0"
          else
            IFS='.' read -ra VER <<< "$VERSION"
            MAJOR="${VER[0]}"
            MINOR="${VER[1]}"
            PATCH="${VER[2]}"
            if [[ -z "$PATCH" ]]; then
              PATCH=0
            else
              PATCH=$((PATCH + 1))
            fi
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          git tag "$NEW_VERSION"
          echo "::set-output name=new_tag::$NEW_VERSION"

      - name: Push new tag
        if: steps.version_tag.outputs.new_tag != ''
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.email "raunel.garciaquintana@emeal.nttdata.com"
          git config --global user.name "QA NTTDATA"
          git config credential.helper store
          git push origin ${{ steps.version_tag.outputs.new_tag }}
