name: Build and Publish Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Accessibility: false
      Platform: Web
      Application: mrc

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: FrontEnd-framework
        path: target/FrontEnd-framework.jar
