name: Build and Publish Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate and apply version tag
        id: version_tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          NEW_VERSION=$(git rev-parse --short HEAD)
          git tag "$NEW_VERSION"
          echo "::set-output name=new_tag::$NEW_VERSION"

      - name: Push new tag
        if: steps.version_tag.outputs.new_tag != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git push origin ${{ steps.version_tag.outputs.new_tag }}

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
