name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      # Step to determine and update the version in the pom.xml
      - name: Update POM version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r -a version_parts <<< "$version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          
          # Determine the type of increment based on commit messages or other criteria
          if git log -1 --pretty=%B | grep -qE '\[major\]'; then
            new_major=$((major + 1))
            new_minor=0
            new_patch=0
            new_version="$new_major.$new_minor.$new_patch"
          elif git log -1 --pretty=%B | grep -qE '\[minor\]'; then
            new_minor=$((minor + 1))
            new_patch=0
            new_version="$major.$new_minor.$new_patch"
          else
            new_patch=$((patch + 1))
            new_version="$major.$minor.$new_patch"
          fi
          
          echo "Current version: $version"
          echo "New version: $new_version"
          sed -i "s|<version>$version</version>|<version>$new_version</version>|g" pom.xml
          
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
